=== dua-x/DAXML_GuidVoyage/config/Config.dtd
<!ELEMENT config (title,tagline, background, nav)>
<!ELEMENT nav (nom, prenom, specialite, section, groupe, mail)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT tagline (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT specialite (#PCDATA)>
<!ELEMENT section (#PCDATA)>
<!ELEMENT groupe (#PCDATA)>
<!ELEMENT mail (#PCDATA)>

=== dua-x/DAXML_GuidVoyage/config/Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "Config.dtd">

<config>

        <title>Explorer le Monde</title>
        <tagline>Votre guide pour explorer le monde</tagline>
        <background>images/header.jpg</background>

    <nav>
        <nom>Douaa</nom>
        <prenom>MAACHOU</prenom>
        <specialite>TI</specialite>
        <section>01</section>
        <groupe>01</groupe>
        <mail>maachoudouaa04@gmail.com</mail>
    </nav>
</config>
